import type { Metadata, Viewport } from "next";
import { Caveat, Sora } from "next/font/google";

import "./globals.css";

/**
 * Sora, the brand's own typeface (design/WonderHome-brand-guidelines.png),
 * self-hosted by next/font so no request ever leaves for a font CDN — the CSP
 * allows fonts from 'self' only, on purpose. `display: swap` keeps text
 * readable in the system face while the file arrives.
 */
const sora = Sora({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sora",
});

/**
 * Caveat, the handwritten accent the mockups close every screen with. Only
 * ever decoration (see ui/script-accent.tsx), so `display: swap` showing the
 * system face for a moment costs nothing a household needs to read.
 */
const caveat = Caveat({
  subsets: ["latin"],
  display: "swap",
  weight: ["500", "600"],
  variable: "--font-caveat",
});

/**
 * Where a shared link resolves from.
 *
 * Open Graph URLs must be absolute — a chat app fetching the card has no
 * page to resolve `/og.png` against — so `metadataBase` supplies the
 * origin. A preview deployment overrides it through `VERCEL_URL`, which is
 * what stops a preview's card silently pointing at production.
 */
const SITE = new URL(
  process.env.NEXT_PUBLIC_SITE_URL ??
    (process.env.VERCEL_ENV === "production"
      ? "https://home.wonderapps.biz"
      : process.env.VERCEL_URL
        ? `https://${process.env.VERCEL_URL}`
        : "https://home.wonderapps.biz"),
);

const DESCRIPTION =
  "WonderHome runs the admin of family life — what needs attention, what was handled, and what is coming — so your family can get on with living it.";

export const metadata: Metadata = {
  metadataBase: SITE,
  title: {
    default: "WonderHome",
    template: "%s · WonderHome",
  },
  description: DESCRIPTION,
  applicationName: "WonderHome",
  manifest: "/manifest.webmanifest",
  /**
   * The card a link turns into in WhatsApp, iMessage and every group chat.
   *
   * Without these a shared link is a bare URL, which is what it was. The
   * image is `og.png`, generated by `npm run brand` from the same geometry
   * the header draws, so it cannot drift from the mark; 1200x630 is what
   * every platform crops from safely.
   *
   * `type: "website"` and an absolute `url` matter to WhatsApp
   * specifically — it is stricter than most about what it will unfurl.
   */
  openGraph: {
    type: "website",
    siteName: "WonderHome",
    title: "WonderHome — Less mental load. More family time.",
    description: DESCRIPTION,
    url: SITE,
    locale: "en_IN",
    images: [
      {
        url: "/og.png",
        width: 1200,
        height: 630,
        alt: "WonderHome — Less mental load. More family time.",
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "WonderHome — Less mental load. More family time.",
    description: DESCRIPTION,
    images: ["/og.png"],
  },
  appleWebApp: { capable: true, title: "WonderHome", statusBarStyle: "default" },
  // Every file here is generated from the same geometry the header renders,
  // by `npm run brand`. The dark tile is offered to browsers that ask for it:
  // a white tile in a dark tab strip is a bright rectangle, not a brand.
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml", media: "(prefers-color-scheme: light)" },
      { url: "/icon-dark.svg", type: "image/svg+xml", media: "(prefers-color-scheme: dark)" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  // One colour, because the app ships one scheme. A dark themeColor here would
  // tint the browser chrome to match a palette the page never renders.
  themeColor: "#fbf8f3",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${sora.variable} ${caveat.variable}`}>
      <body>{children}</body>
    </html>
  );
}
