import type { Translate } from "@wonderhome/core/i18n/translate";

import type { MealFormLabels } from "../_components/meal-forms";

/** Placeholders the sheets fill in on the client with a recipe's or an ingredient's own words. */
const KEEP = { name: "{name}", minutes: "{minutes}", serves: "{serves}", items: "{items}" };

/** Every meal sheet's words in the viewer's language (story 22-004). */
export function mealFormLabels(t: Translate): MealFormLabels {
  return {
    slots: {
      breakfast: t("reminder.meal.slot.breakfast"),
      lunch: t("reminder.meal.slot.lunch"),
      snack: t("reminder.meal.slot.snack"),
      dinner: t("reminder.meal.slot.dinner"),
    },
    preferenceKinds: {
      preference: t("mealForm.kind.preference"),
      dislike: t("mealForm.kind.dislike"),
      allergy: t("mealForm.kind.allergy"),
      medical: t("mealForm.kind.medical"),
      ethical: t("mealForm.kind.ethical"),
    },
    plan: t("mealForm.plan"),
    planDescription: t("mealForm.planDescription"),
    mealName: t("mealForm.mealName"),
    mealPlaceholder: t("mealForm.mealPlaceholder"),
    essential: t("mealForm.essential"),
    essentialPlaceholder: t("mealForm.essentialPlaceholder"),
    fillLater: t("mealForm.fillLater"),
    backToPicking: t("mealForm.backToPicking"),
    addMeal: t("mealForm.addMeal"),
    adding: t("common.adding"),
    fromRecipe: t("mealForm.fromRecipe"),
    oneOff: t("mealForm.oneOff"),
    readyToCook: t("mealForm.readyToCook"),
    missingIngredient: t("mealForm.missingIngredient"),
    recipeOption: t("mealForm.recipeOption", KEEP),
    addNewMeal: t("mealForm.addNewMeal"),
    slot: t("mealForm.slot"),
    date: t("mealForm.date"),
    readyBy: t("mealForm.readyBy"),
    cook: t("mealForm.cook"),
    nobodyYet: t("mealForm.nobodyYet"),
    planSubmit: t("mealForm.planSubmit"),
    planning: t("mealForm.planning"),
    attach: t("mealForm.attach"),
    attachTitle: t("mealForm.attachTitle"),
    attachDescription: t("mealForm.attachDescription"),
    whichRecipe: t("mealForm.whichRecipe"),
    attachSubmit: t("mealForm.attachSubmit"),
    attaching: t("mealForm.attaching"),
    addRecipe: t("mealForm.addRecipe"),
    recipeTitle: t("mealForm.recipeTitle"),
    recipeDescription: t("mealForm.recipeDescription"),
    recipeName: t("mealForm.recipeName"),
    cuisine: t("mealForm.cuisine"),
    cuisinePlaceholder: t("mealForm.cuisinePlaceholder"),
    activeMinutes: t("mealForm.activeMinutes"),
    totalMinutes: t("mealForm.totalMinutes"),
    serves: t("mealForm.serves"),
    optional: t("mealForm.optional"),
    optionalPlaceholder: t("mealForm.optionalPlaceholder"),
    nutrients: t("mealForm.nutrients"),
    calories: t("mealForm.calories"),
    protein: t("mealForm.protein"),
    carbs: t("mealForm.carbs"),
    fat: t("mealForm.fat"),
    method: t("mealForm.method"),
    methodPlaceholder: t("mealForm.methodPlaceholder"),
    addPreference: t("mealForm.addPreference"),
    preferenceTitle: t("mealForm.preferenceTitle"),
    preferenceDescription: t("mealForm.preferenceDescription"),
    who: t("mealForm.who"),
    wholeHousehold: t("meals.wholeHousehold"),
    kind: t("mealForm.kind"),
    subject: t("mealForm.subject"),
    subjectPlaceholder: t("mealForm.subjectPlaceholder"),
    suggest: t("mealForm.suggest"),
    suggestTitle: t("mealForm.suggestTitle"),
    suggestDescription: t("mealForm.suggestDescription"),
    forDay: t("mealForm.forDay"),
    check: t("mealForm.check"),
    checking: t("mealForm.checking"),
    stillNeeds: t("mealForm.stillNeeds", KEEP),
    runningLow: t("mealForm.runningLow", KEEP),
    addToPlan: t("mealForm.addToPlan"),
  };
}
