import type { SupabaseClient } from "@supabase/supabase-js";

import { auditChange } from "../api/audit";
import { ApiError } from "../api/errors";
import type {
  HomeSendExtraction,
  HomeSendItem,
  HomeSendKind,
  HomeSendSecurityStatus,
  HomeSendSource,
  HomeSendStatus,
} from "./items";

/**
 * Reading and writing HomeSend intake (Phase C).
 *
 * Every write here only ever touches `home_send_items` — routing an item
 * into a real domain table is a separate call, made by the caller, to that
 * domain's own governed create function (`createObligation`,
 * `createSchoolItem`, `createConsumable`). Nothing in this file writes
 * outside its own table.
 */

type Row = Record<string, unknown>;

function fromRow(row: Row): HomeSendItem {
  return {
    id: row.id as string,
    householdId: row.household_id as string,
    createdByMemberId: row.created_by_member_id as string,
    source: row.source as HomeSendSource,
    filePath: (row.file_path as string | null) ?? null,
    rawText: (row.raw_text as string | null) ?? null,
    status: row.status as HomeSendStatus,
    classifiedKind: (row.classified_kind as HomeSendKind | null) ?? null,
    extracted: (row.extracted as HomeSendExtraction | null) ?? null,
    routedTable: (row.routed_table as string | null) ?? null,
    routedId: (row.routed_id as string | null) ?? null,
    securityStatus: row.security_status as HomeSendSecurityStatus,
    createdAt: row.created_at as string,
  };
}

const SELECT_COLUMNS =
  "id, household_id, created_by_member_id, source, file_path, raw_text, status, classified_kind, extracted, routed_table, routed_id, security_status, created_at";

export async function listHomeSendItems(
  supabase: SupabaseClient,
  householdId: string,
  options?: { status?: HomeSendStatus },
): Promise<HomeSendItem[]> {
  let query = supabase
    .from("home_send_items")
    .select(SELECT_COLUMNS)
    .eq("household_id", householdId)
    .order("created_at", { ascending: false });
  if (options?.status) query = query.eq("status", options.status);

  const { data, error } = await query;
  if (error) throw new Error(`listHomeSendItems failed: ${error.code ?? "unknown"}`);
  return (data ?? []).map((row) => fromRow(row as Row));
}

export type CreateHomeSendItemInput = {
  /** Pre-generated by the caller so it can double as the storage path segment for an upload. */
  id: string;
  householdId: string;
  createdByMemberId: string;
  source: HomeSendSource;
  filePath?: string | null;
  rawText?: string | null;
  /** Defaults to `not_applicable` (pasted text has no file to check). */
  securityStatus?: HomeSendSecurityStatus;
};

export async function createHomeSendItem(
  supabase: SupabaseClient,
  input: CreateHomeSendItemInput,
): Promise<HomeSendItem> {
  const securityStatus = input.securityStatus ?? "not_applicable";

  const { data, error } = await supabase
    .from("home_send_items")
    .insert({
      id: input.id,
      household_id: input.householdId,
      created_by_member_id: input.createdByMemberId,
      source: input.source,
      file_path: input.filePath ?? null,
      raw_text: input.rawText ?? null,
      security_status: securityStatus,
    })
    .select(SELECT_COLUMNS)
    .single();

  if (error) {
    if (error.code === "42501") throw ApiError.forbidden("You cannot send items to this household.");
    throw new Error(`createHomeSendItem failed: ${error.code ?? "unknown"}`);
  }

  await auditChange({
    householdId: input.householdId,
    actorMemberId: input.createdByMemberId,
    eventType: "homesend.intake_received",
    targetTable: "home_send_items",
    targetId: input.id,
    metadata: { source: input.source },
  });
  if (securityStatus === "rejected") {
    await auditChange({
      householdId: input.householdId,
      actorMemberId: input.createdByMemberId,
      eventType: "homesend.security_rejected",
      targetTable: "home_send_items",
      targetId: input.id,
      metadata: { source: input.source },
    });
  }

  return fromRow(data as Row);
}

export async function setHomeSendClassification(
  supabase: SupabaseClient,
  householdId: string,
  itemId: string,
  input: { classifiedKind: HomeSendKind; extracted: HomeSendExtraction },
): Promise<void> {
  const { error } = await supabase
    .from("home_send_items")
    .update({ status: "classified", classified_kind: input.classifiedKind, extracted: input.extracted })
    .eq("household_id", householdId)
    .eq("id", itemId);

  if (error) throw new Error(`setHomeSendClassification failed: ${error.code ?? "unknown"}`);
}

export async function routeHomeSendItem(
  supabase: SupabaseClient,
  householdId: string,
  itemId: string,
  input: { routedTable: string; routedId: string },
): Promise<void> {
  const { error } = await supabase
    .from("home_send_items")
    .update({ status: "routed", routed_table: input.routedTable, routed_id: input.routedId })
    .eq("household_id", householdId)
    .eq("id", itemId);

  if (error) throw new Error(`routeHomeSendItem failed: ${error.code ?? "unknown"}`);
}

/** The other half of sending something in (CLAUDE.md rule 12): saying it was not worth acting on. */
export async function dismissHomeSendItem(
  supabase: SupabaseClient,
  householdId: string,
  itemId: string,
  actorMemberId: string,
): Promise<void> {
  const { error } = await supabase
    .from("home_send_items")
    .update({ status: "dismissed" })
    .eq("household_id", householdId)
    .eq("id", itemId);

  if (error) throw new Error(`dismissHomeSendItem failed: ${error.code ?? "unknown"}`);

  await auditChange({
    householdId,
    actorMemberId,
    eventType: "homesend.dismissed",
    targetTable: "home_send_items",
    targetId: itemId,
  });
}

/** Flips a routed item's status once its one change has been undone — the record of what was routed (`routed_table`/`routed_id`) is kept, never erased. */
export async function markHomeSendUndone(
  supabase: SupabaseClient,
  householdId: string,
  itemId: string,
): Promise<void> {
  const { error } = await supabase
    .from("home_send_items")
    .update({ status: "undone" })
    .eq("household_id", householdId)
    .eq("id", itemId);

  if (error) throw new Error(`markHomeSendUndone failed: ${error.code ?? "unknown"}`);
}
