-- Outbound webhooks (story 18-007): signed, versioned events a household's
-- own integration can subscribe to.
--
-- `household_webhooks` holds a signing secret the same way
-- `household_ai_credentials` holds a model key: no client reach at all, on
-- purpose, admin included -- not read, and (see the policy comment below)
-- not written either. The secret is generated once (or rotated) and handed
-- back in that single response; after that it is never readable again
-- through PostgREST, only usable by the service-role connection every
-- write and every delivery already goes through. A member's own read of
-- "what webhooks are configured" goes through `list_webhook_subscriptions()`
-- below, which answers everything except the one column that matters for
-- this exception.
--
-- `webhook_deliveries` is the delivery queue the worker (`deliver.ts`) drains
-- on a schedule. It is not a household's to read at all -- not even the
-- admin who configured the webhook -- because a payload in flight can carry
-- the same household content the subscription itself was built to receive,
-- and this table exists only to get it there reliably, not to be a second
-- copy of it visible in the app. Same "no client reach, service role only"
-- shape `homesend_share_handoffs` already uses.

create table public.household_webhooks (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  url text not null check (length(trim(url)) between 1 and 2000),
  -- HMAC-SHA256 signing key, base64url. Generated by the server
  -- (`webhooks/repository.ts`'s `generateWebhookSecret`), never chosen by a
  -- household -- the same reasoning `homesend_addresses`' address token uses.
  secret text not null check (length(trim(secret)) >= 32),
  event_types text[] not null check (cardinality(event_types) >= 1),
  status text not null default 'active' check (status in ('active', 'disabled')),
  created_by_member_id uuid references public.household_members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  rotated_at timestamptz,
  disabled_at timestamptz
);

comment on table public.household_webhooks is
  'A household''s own outbound event subscription. Deliberately has no client reach at all, read or write: the signing secret is generated once and returned directly, never read back through PostgREST, and every write goes through the admin/service-role client with its own application-level admin check -- see list_webhook_subscriptions() for the member-safe read.';

alter table public.household_webhooks enable row level security;

create index household_webhooks_household_idx on public.household_webhooks (household_id);

create trigger household_webhooks_set_updated_at
  before update on public.household_webhooks
  for each row execute function wh.set_updated_at();

create trigger household_webhooks_member_valid
  before insert or update on public.household_webhooks
  for each row execute function wh.assert_meal_member_in_household('created_by_member_id');

-- No RLS write path at all, admin included -- a deliberate change from an
-- earlier version of this migration that gave `authenticated` its own
-- insert/update/delete policies gated on `wh.is_household_admin`. Two
-- things killed that design before it shipped:
--
--   1. `webhooks/repository.ts` never writes through the household's own
--      client anyway -- every write (create/rotate/disable/enable) already
--      goes through the admin/service-role client, with the admin check
--      done in application code (`requireAdmin`), because RETURNING the
--      freshly-written secret needs that client regardless. So a household
--      session's own write access here was never exercised by anything
--      real -- pure unused surface.
--   2. It was also a landmine. Empirically verified against a scratch
--      database: an UPDATE or DELETE whose WHERE clause inspects an actual
--      column value (`where id = '...'`, not a literal like `where true`)
--      additionally requires SELECT-level visibility on that row for
--      Postgres to decide whether it matches -- not just the UPDATE/DELETE
--      policy's own USING clause. With no SELECT policy on this table (the
--      whole point, so the secret is never readable), that visibility
--      check always fails, so `UPDATE ... WHERE id = '<this one row>'`
--      silently matches and changes zero rows for every session, admin
--      included -- only a blanket, unconditional `UPDATE` with no WHERE at
--      all would have gone through. A policy that only "works" when nobody
--      names which row they mean is not a policy worth keeping.
--
-- So: no client reach at all, the same shape `webhook_deliveries` below
-- already uses. The one policy that exists is only so this is not "no
-- policy at all" (`scripts/test-tenant-isolation-rls.mjs` treats that as
-- unprotected), not because anything legitimately reads through it.
create policy household_webhooks_no_client_access
  on public.household_webhooks for select
  to authenticated
  using (false);

/**
 * What a member may know about the household's webhooks, without ever
 * returning the signing secret -- the same "answer what's needed, never the
 * secret" shape `ai_credential_status()` already uses.
 */
create or replace function public.list_webhook_subscriptions(p_household_id uuid)
returns table (
  id uuid,
  url text,
  event_types text[],
  status text,
  created_at timestamptz,
  rotated_at timestamptz,
  disabled_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select w.id, w.url, w.event_types, w.status, w.created_at, w.rotated_at, w.disabled_at
  from public.household_webhooks w
  where w.household_id = p_household_id and wh.is_member(p_household_id)
  order by w.created_at desc;
$$;

comment on function public.list_webhook_subscriptions is
  'Every webhook configured for a household, minus the signing secret. Any member may call it; only an administrator may write to the table it reads.';

revoke all on function public.list_webhook_subscriptions(uuid) from public, anon;
grant execute on function public.list_webhook_subscriptions(uuid) to authenticated;

create table public.webhook_deliveries (
  id uuid primary key default gen_random_uuid(),
  webhook_id uuid not null references public.household_webhooks(id) on delete cascade,
  household_id uuid not null references public.households(id) on delete cascade,
  event_type text not null,
  -- The event's own id, distinct from this delivery row's id: a retried
  -- delivery is a new attempt at the same event, and a subscriber's
  -- idempotency check (deduping on this value) depends on it staying fixed
  -- across attempts.
  event_id uuid not null,
  payload jsonb not null,
  status text not null default 'pending' check (status in ('pending', 'delivered', 'failed', 'exhausted')),
  attempt_count integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

comment on table public.webhook_deliveries is
  'The outbound delivery queue deliverPendingWebhooks() drains. Never reachable from any household session, admin included -- a payload in flight can carry the same content the subscription exists to receive, and this table is not a second copy of it for the app to show.';

alter table public.webhook_deliveries enable row level security;

create index webhook_deliveries_due_idx on public.webhook_deliveries (next_attempt_at) where status = 'pending';
create index webhook_deliveries_webhook_idx on public.webhook_deliveries (webhook_id);

-- No client, signed in or not, has a legitimate reason to read this table.
-- This policy exists only so it is not "no policy at all"
-- (scripts/test-tenant-isolation-rls.mjs treats that as unprotected) -- the
-- same shape `audit_events`/`homesend_share_handoffs` already use.
create policy webhook_deliveries_no_client_access
  on public.webhook_deliveries for select
  to authenticated
  using (false);

notify pgrst, 'reload schema';
